#
# This config-file is only needed for staging. Instead of changing the url
# everytime you work locally on the project, you start both config-files, overwriting
# the first one with the development variables needed.
#
# Start development with › $ jekyll serve --config _config.yml,_config_staging.yml

url: 'https://privacybydesign.foundation:4432'
baseurl: ''
urlimg: 'https://privacybydesign.foundation:4432/images/'
